apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# Log all create, update, patch, and delete activity for all resources at the Request level
- level: Request
  verbs: ["create", "update", "delete", "patch"]
  resources:
  - group: ""
    resources: ["*"]
# Log activity for secrets at the RequestResponse level
- level: RequestResponse
  resources: 
  - group: ""
    resources: ["secrets"]
# Log activity from the system:nodes userGroup, at the RequestResponse level
- level: Metadata
  userGroups: ["system:nodes"]
